# -*- coding: utf-8 -*-
"""Bi-Section.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrr44jPKlGJK7iwobs5cZv8hqeE4pkxB
"""

def f(x):
  return x*x-4*x-10

xValue = []
yValue = []

i = -6.0
while i<=6.0:
  xValue.append(i)
  yValue.append(f(i))
  i = i+0.25

print(xValue)
print(yValue)

import matplotlib.pyplot as plt

plt.plot(xValue, yValue)
plt.grid()
plt.title("Graph of f(x) = x*x-4*x-10")
# plt.xlabel('x')
# plt.ylabel('f(x)')
plt.axhline(y=0, color = "black")
plt.axvline(x=0, color = "black")
plt.show()

x1 = -2.0
x2 = 0.0

def bisectionMethod(x1, x2):
  for iteration in range(0, 100):
    fx1 = f(x1)
    fx2 = f(x2)
    print("Iteration: ", iteration+1)
    print("x1: ", x1)
    print("x2: ", x2)

    if fx1*fx2 >= 0:
      print("No root found.")
      break
    else:
      x0 = (x1+x2)/2
      fx0 = f(x0)
      if fx0 == 0:
        print("root found")
        return x0

      else:
        if fx0*fx1 < 0:
          x2 = x0
        else:
          x1 = x0
  return x0

bisectionMethod(x1,x2)

