# -*- coding: utf-8 -*-
"""False Position Method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b56EmfORd0wK0TuAuK4w0rFkKUrBO3Tk
"""

def f(x):
  return x**2-x-2

xValue = []
yValue = []

i=1
while i<=3:
    xValue.append(i)
    yValue.append(f(i))
    i+=0.25
print(xValue)
print(yValue)

import matplotlib.pyplot as plt

plt.plot(xValue,yValue)
plt.grid()
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.show()

x1 = 1
x2 = 3

def false_position(x1,x2):
  for i in range(0,100):
    fx1 = f(x1)
    fx2 = f(x2)

    if fx1*fx2 >= 0:
      print("No Root Found.")
      break
    else:
      x0 = x1 - (fx1*(x2-x1)/(fx2-fx1))
      fx0 = f(x0)
      if fx0 == 0:
        print("Root Found.")
        return x0
      elif fx0*fx1 < 0:
        x2 = x0
      else:
        x1 = x0
  return x0

false_position(x1,x2)